name: 编译linux_jazzy_aarch64
# 因为aarch64 用qemu在docker中编译很慢
# 并且aarch64的docker用来貌似没有实际用途
# 所以这里直接使用宿主机编译
on:
  push:
  workflow_dispatch:

jobs:
  build_ros2_ubuntu:
    permissions:
      contents: write
    strategy:
      matrix:
        ros2_version: [jazzy]
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}-arm

    steps:
      - name: 将存储库签出到运行器
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: 脚本准备
        run: |
          cp ./script/*.sh  .
          cp -r ./script/${{ matrix.target }}_linux/*  .

      - name: 计算编译参数
        id: cid
        run: |

          RUN_OS="${{ matrix.os }}"
          RUN_OS="${RUN_OS//-/_}"
          ROS2_COMMIT_ID=$(git ls-remote https://github.com/ros2/ros2.git ${{ matrix.ros2_version }}-release | head -n 1 | awk '{print $1}')
          TAG_KEY="${{ github.sha }}-${ROS2_COMMIT_ID}"
          TAG_NAME="ros2-$(date +'%Y-%m-%d_%H%M')"
          TAG_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${TAG_KEY}"
          ROS2_NAME="ros2-${RUN_OS}-${{ matrix.ros2_version }}-aarch64"


          echo "ros2_name=${ROS2_NAME}" >> $GITHUB_OUTPUT
          echo "tag_key=${TAG_KEY}" >> $GITHUB_OUTPUT
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "tag_url=${TAG_URL}" >> $GITHUB_OUTPUT

          echo "ROS2提交哈希: $ROS2_COMMIT_ID"
          echo "编译名称: $ROS2_NAME"
          echo "TAG哈希:${TAG_KEY}"
          echo "TAG名称:${TAG_NAME}"
          echo "TAG URL:${TAG_URL}"

      - name: 判断是否需要构建
        id: check
        run: |
          # 调用GitHub API检查该Tag的Release是否存在
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ steps.cid.outputs.tag_url }})

          if [ $HTTP_CODE -eq 200 ]; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
            echo "Release已存在,跳过构建"
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
            echo "需要构建镜像"
          fi

      - name: 编译并打包构建产物
        if: steps.check.outputs.skip_build == 'false'
        run: |
          # 先创建环境
          sudo -E /bin/bash $GITHUB_WORKSPACE/build.sh -r "${{ matrix.ros2_version }}"
          sudo mv $GITHUB_WORKSPACE/ros2/install $GITHUB_WORKSPACE

          tar -cavf ${{ steps.cid.outputs.ros2_name }}.tar.bz2 install
          sha256sum ${{ steps.cid.outputs.ros2_name }}.tar.bz2 > ${{ steps.cid.outputs.ros2_name }}.tar.bz2.sha256

      - name: 上传编译结果
        if: steps.check.outputs.skip_build == 'false'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.cid.outputs.tag_key }}
          name: ${{ steps.cid.outputs.tag_name }}
          prerelease: false
          draft: false
          generate_release_notes: true
          files: |
            ${{ steps.cid.outputs.ros2_name }}.tar.bz2
            *.sha256
