name: 编译linux_jazzy_amd64

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        ros2_version: [jazzy]
        docker_base: [ubuntu:24.04, ubuntu:22.04]
        target: [amd64]

    steps:
      - name: 将存储库签出到运行器
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: 脚本准备
        run: |
          cp ./script/*.sh  .
          cp -r ./script/${{ matrix.target }}_linux/*  .

      - name: 计算编译参数
        id: cid
        run: |

          DOCKER_BASE="${{ matrix.docker_base }}"
          DOCKER_BASE="${DOCKER_BASE//:/_}"
          ROS2_COMMIT_ID=$(git ls-remote https://github.com/ros2/ros2.git ${{ matrix.ros2_version }}-release | head -n 1 | awk '{print $1}')
          TAG_KEY="${{ github.sha }}-${ROS2_COMMIT_ID}"
          TAG_NAME="ros2-$(date +'%Y-%m-%d_%H%M')"
          TAG_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${TAG_KEY}"
          ROS2_NAME="ros2-${DOCKER_BASE}-${{ matrix.ros2_version }}-${{ matrix.target }}"
          IMAGE_NAME="ros2-docker-image-${DOCKER_BASE}-${{ matrix.ros2_version }}-${{ matrix.target }}"
          DEP_DATA="dep-${DOCKER_BASE}-${{ matrix.ros2_version }}-${{ matrix.target }}"

          echo "ros2_name=${ROS2_NAME}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tag_key=${TAG_KEY}" >> $GITHUB_OUTPUT
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "tag_url=${TAG_URL}" >> $GITHUB_OUTPUT
          echo "dep_data=${DEP_DATA}" >> $GITHUB_OUTPUT

          echo "ROS2提交哈希: $ROS2_COMMIT_ID"
          echo "镜像名称: $IMAGE_NAME"
          echo "编译名称: $ROS2_NAME"
          echo "依赖文件名称: $DEP_DATA"
          echo "TAG哈希:${TAG_KEY}"
          echo "TAG名称:${TAG_NAME}"
          echo "TAG URL:${TAG_URL}"

      - name: 判断是否需要构建
        id: check
        run: |
          # 调用GitHub API检查该Tag的Release是否存在
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ steps.cid.outputs.tag_url }})

          if [ $HTTP_CODE -eq 200 ]; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
            echo "Release已存在,跳过构建"
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
            echo "需要构建镜像"
          fi

      - name: 设置Buildx
        if: steps.check.outputs.skip_build == 'false'
        uses: docker/setup-buildx-action@v4

      - name: 编译和导出镜像 ${{ matrix.target }}
        if: steps.check.outputs.skip_build == 'false'
        run: |
          docker buildx create --name builder --use
          docker buildx build \
            --platform linux/${{ matrix.target }} \
            -t ros2-build:${{ matrix.target }} \
            --build-arg ROS2_VERSION=${{ matrix.ros2_version }} \
            --build-arg BASE_IMAGE=${{ matrix.docker_base }} \
            --output type=docker,dest=${{ steps.cid.outputs.image_name }}.tar.zst,compression=zstd,compression-level=9 \
            .

      - name: 编译并打包构建产物
        if: steps.check.outputs.skip_build == 'false'
        run: |
          /bin/bash $GITHUB_WORKSPACE/run_build.sh -r "${{ matrix.ros2_version }}" -i "${{ steps.cid.outputs.image_name }}.tar.zst" -t ${{ matrix.target }}

          mv dep_data.txt  ${{ steps.cid.outputs.dep_data}}.txt
          mv ros2.tar.bz2 ${{ steps.cid.outputs.ros2_name }}.tar.bz2

          sha256sum ${{ steps.cid.outputs.ros2_name }}.tar.bz2 > ${{ steps.cid.outputs.ros2_name }}.tar.bz2.sha256

      # release 单文件最大2g
      - name: 压缩Docker镜像
        if: steps.check.outputs.skip_build == 'false'
        run: |
          image_name="${{ steps.cid.outputs.image_name }}"
          split -b 1900M ${image_name}.tar.zst ${image_name}-part-
          sha256sum ${image_name}.tar.zst > ${image_name}.tar.zst.sha256
          cat "${image_name}.tar.zst.sha256"
          rm -rf ${image_name}.tar.zst

      - name: 上传编译结果
        if: steps.check.outputs.skip_build == 'false'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.cid.outputs.tag_key }}
          name: ${{ steps.cid.outputs.tag_name }}
          prerelease: false
          draft: false
          generate_release_notes: true
          files: |
            ${{ steps.cid.outputs.image_name }}-part-*
            ${{ steps.cid.outputs.ros2_name }}.tar.bz2
            ${{ steps.cid.outputs.dep_data}}.txt
            *.sha256
