name: 编译ros2
run-name: ${{ github.actor }}
on:
  workflow_run:
    workflows: ["编译并导出镜像"]
    types:
      - completed
  # push:
  workflow_dispatch:
    inputs:
      ros2_version:
        description: "编译的ros2版本"
        type: string
        required: false
      rebuild:
        description: '强制重新生成'
        required: false
        type: boolean
env:
  ROS2_VERSION: ${{ inputs.ros2_version || 'jazzy' }}
  REBUILD: ${{ inputs.rebuild }}

jobs:
  build_ros2_ubuntu:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [amd64, arm64]
    steps:
      - name: 将存储库签出到运行器
        uses: actions/checkout@v4
        with:
          set-safe-directory: "${GITHUB_WORKSPACE}/build_ros2"

      - name: 计算哈希
        id: hash
        run: |
          IMAGE_HASH=$(find . -name "Dockerfile" -o -name "build_image.yaml" -o -name "build_docker_env.sh" \
            -type f -exec md5sum {} \; | sort | md5sum | cut -d' ' -f1)
          ROS2_HASH=$(find . -name "build.sh" -o -name "build.yaml" -o -name "build.ps1" -o -name "run_build.sh" \
            -type f -exec md5sum {} \; | sort | md5sum | cut -d' ' -f1)
          echo "image_hash=$IMAGE_HASH" >> $GITHUB_OUTPUT
          echo "ros2_hash=$ROS2_HASH$IMAGE_HASH" >> $GITHUB_OUTPUT
          echo "IMAGE哈希: $IMAGE_HASH"
          echo "ROS2哈希: $ROS2_HASH"

      - name: 检查缓存
        id: cache
        uses: actions/cache@v4
        with:
          path: ros2-${{ env.ROS2_VERSION }}-${{ matrix.target }}.tar.bz2
          key: ros2-${{ env.ROS2_VERSION }}-${{ matrix.target }}-${{ steps.hash.outputs.ros2_hash }}

      - name: 判断是否需要构建
        id: check
        run: |
          if [[ "$REBUILD" == "true" ]]; then
            echo "skip_build=false" >> $GITHUB_OUTPUT
            echo "强制重新编译"
          elif [[ "${{ steps.cache.outputs.cache-hit }}" == "true" ]]; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
            echo "缓存命中，跳过构建"
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
            echo "需要构建镜像"
          fi

      - name: 恢复编译镜像
        id: restore
        uses: actions/cache/restore@v6
        with:
          path: ros2-build-image-${{ matrix.target }}.tar
          key: docker-${{ matrix.target }}-${{ steps.hash.outputs.image_hash }}
          fail-on-cache-miss: true

      - name: 设置QEMU
        if:  steps.check.outputs.skip_build == 'false' && matrix.target == 'arm64'
        uses: docker/setup-qemu-action@v4

      - name: 设置Buildx
        if: steps.check.outputs.skip_build == 'false'
        uses: docker/setup-buildx-action@v4

      - name: 编译并打包构建产物
        if: steps.check.outputs.skip_build == 'false'
        run: |
          echo "FILE_DATE=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          /bin/bash $GITHUB_WORKSPACE/run_build.sh -r "${ROS2_VERSION}" -i "ros2-build-image-${{ matrix.target }}.tar" -t ${{ matrix.target }}

      - name: 上传所有构建产物
        if: steps.check.outputs.skip_build == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: ros2-${{ env.ROS2_VERSION }}-${{ matrix.target }}
          path: ros2-${{ env.ROS2_VERSION }}-${{ matrix.target }}.tar.bz2
          retention-days: 30
          if-no-files-found: error
          
  # build_ros2_windows:
  #   runs-on: windows-2022
  #   steps:
  #     - name: 将存储库签出到运行器
  #       uses: actions/checkout@v4
  #       with:
  #         set-safe-directory: "${GITHUB_WORKSPACE}/build_ros2"
  #     - name: 编译
  #       id: windows_build
  #       run: |
  #         Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
  #         New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
  #         echo "FILE_DATE=$(date +'%Y-%m-%d_%H%M')" >> $env:GITHUB_ENV
  #         & $env:GITHUB_WORKSPACE/build.ps1 -d "$env:ROS2_VERSION" -g "$env:MIRROR_GITHUB" -r "$env:MIRROR_RAW"

  #     - name: 打包
  #       if: always()
  #       run: |
  #         Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
  #         & $env:GITHUB_WORKSPACE/package.ps1

  #     - name: 编译结果
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ros2_windows_${{ env.FILE_DATE }}
  #         path: ${{ env.OUT_FILE }}
  #         include-hidden-files: true
  #         compression-level: 9

  #     - name: 编译日志
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: ros2_windows_build_log_${{ env.FILE_DATE }}
  #         path: ${{ env.LOG_FILE }}
  #         include-hidden-files: true
  #         compression-level: 9

  #     - name: 打包所有环境
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: ros2_windows_all_env_${{ env.FILE_DATE }}
  #         path: ${{ env.ALL_ENV }}
  #         include-hidden-files: true
  #         compression-level: 9
