name: 创建含源码的完整编译环境

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ros2_version: [jazzy]
        docker_base: [ubuntu:22.04, ubuntu:24.04]
        target: [amd64, arm64]
        exclude:
          # 这个会段错误 暂未解决
          - docker_base: ubuntu:22.04
            target: arm64
            ros2_version: jazzy

    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: 计算上下文ID
        id: cid
        run: |
          DOCKER_BASE="${{ matrix.docker_base }}"
          DOCKER_BASE="${DOCKER_BASE//:/_}"
          ROS2_COMMIT_ID=$(git ls-remote https://github.com/ros2/ros2.git ${{ matrix.ros2_version }}-release | head -n 1 | awk '{print $1}')
          IMAGE_HASH=$(/bin/bash ./calculate_hash.sh Dockerfile full_compilation_environment.yaml build_docker_env.sh)
          IMAGE_KEY="ros2-docker-image-${DOCKER_BASE}-${{ matrix.ros2_version }}-${{ matrix.target }}-${IMAGE_HASH}-${ROS2_COMMIT_ID}"
          IMAGE_NAME="ros2-docker-image-${DOCKER_BASE}-${{ matrix.ros2_version }}-${{ matrix.target }}"
          # 上下文hash
          CONTEXT_HASH=$(/bin/bash ./calculate_hash.sh Dockerfile *.yaml *.sh *.cmake)

          echo "context_hash=$CONTEXT_HASH" >> $GITHUB_OUTPUT
          echo "image_key=$IMAGE_KEY" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "ros2_commit_id=$ROS2_COMMIT_ID" >> $GITHUB_OUTPUT

          echo "ROS2提交哈希: $ROS2_COMMIT_ID"
          echo "镜像哈希: $IMAGE_KEY"
          echo "镜像名称: $IMAGE_NAME"

      - name: 检查缓存
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.cid.outputs.image_name }}.tar.zst
          lookup-only: true
          key: ${{ steps.cid.outputs.image_key }}

      - name: 判断是否需要构建
        id: check
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" == "true" ]; then
            echo "skip_build=true" >> $GITHUB_OUTPUT
            echo "缓存命中，跳过构建"
          else
            echo "skip_build=false" >> $GITHUB_OUTPUT
            echo "需要构建镜像"
          fi

      - name: 设置QEMU
        if: steps.check.outputs.skip_build == 'false' && matrix.target == 'arm64'
        uses: docker/setup-qemu-action@v4
        with:
          reset: true

      - name: 设置Buildx
        if: steps.check.outputs.skip_build == 'false'
        uses: docker/setup-buildx-action@v4

      - name: 编译和导出镜像 ${{ matrix.target }}
        if: steps.check.outputs.skip_build == 'false'
        run: |
          docker buildx create --name builder --use
          docker buildx build \
            --platform linux/${{ matrix.target }} \
            -t ros2-build:${{ matrix.target }} \
            --build-arg ROS2_VERSION=${{ matrix.ros2_version }} \
            --build-arg BASE_IMAGE=${{ matrix.docker_base }} \
            --output type=docker,dest=${{ steps.cid.outputs.image_name }}.tar.zst,compression=zstd,compression-level=9 \
            .

      - name: 保存${{ matrix.target }}镜像到缓存
        if: steps.check.outputs.skip_build == 'false'
        uses: actions/cache/save@v6
        with:
          path: ${{ steps.cid.outputs.image_name }}.tar.zst
          key: ${{ steps.cid.outputs.image_key }}

      - name: 上传${{ matrix.target }}镜像
        if: steps.check.outputs.skip_build == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.cid.outputs.image_name }}
          path: ${{ steps.cid.outputs.image_name }}.tar.zst
          retention-days: 7
          if-no-files-found: error

      - name: 保存需要传递的参数
        run: |
          echo "ros2_version=${{ matrix.ros2_version }}" > flow_run_id_arg
          echo "image_key=${{ steps.cid.outputs.image_key }}" >> flow_run_id_arg
          echo "image_name=${{ steps.cid.outputs.image_name }}" >> flow_run_id_arg
          echo "ros2_commit_id=${{ steps.cid.outputs.ros2_commit_id }}" >> flow_run_id_arg

          echo "提交hash: ${{ github.sha }} 流程ID: ${{ github.run_id }} 传递参数: $(cat flow_run_id_arg)"

      - name: 流程参数传递
        uses: actions/cache/save@v6
        with:
          path: flow_run_id_arg
          key: ${{ steps.cid.outputs.context_hash }}-${{ matrix.docker_base }}-${{ matrix.target }}
