name: 上传Release

on:
  # push:
  workflow_dispatch:
  workflow_run:
    workflows: ["创建含源码的完整编译环境", "编译Linux Ros2"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [amd64, arm64]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: 获取流程参数文件
        id: restore
        uses: actions/cache/restore@v6
        with:
          path: flow_run_id_arg_${{ matrix.target }}
          key: ${{ github.sha }}-${{ github.event.workflow_run.id }}
          fail-on-cache-miss: true

      - name: 还原参数文件
        id: args
        run: |
          # 逐行读取并输出
          while IFS='=' read -r key value; do
            # 跳过空行和注释
            [[ -z "$key" || "$key" =~ ^# ]] && continue

            # 去除可能的空格
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)

            # 输出到GITHUB_OUTPUT
            echo "${key}=${value}" >> $GITHUB_OUTPUT
            declare "${key}=${value}"
            echo "流程参数:${key}=${value}"
          done < flow_run_id_arg_${{ matrix.target }}

          TAG_HASH=$(/bin/bash ./calculate_hash.sh Dockerfile *.yaml *.sh *.cmake -e release.yaml)
          TAG_NAME="ros2-${ros2_version}-$TAG_HASH-$ros2_commit_id"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

          echo "TAG名称:${TAG_NAME}"

          # 处理一下变量不存在的情况
          if [ -z "$image_name" ]; then
              echo "image_name=none" >> $GITHUB_OUTPUT
              echo "image_key=none" >> $GITHUB_OUTPUT
          fi
          if [ -z "$ros2_linux_name" ]; then
              echo "ros2_linux_name=none" >> $GITHUB_OUTPUT
              echo "ros2_linux_key=none" >> $GITHUB_OUTPUT
          fi

      - name: 检查docker缓存
        id: docker_cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ steps.args.outputs.image_name }}.tar
          key: ${{ steps.args.outputs.image_key }}
          fail-on-cache-miss: false

      - name: 检查linux ros2缓存
        id: ros2_linux_cache
        uses: actions/cache/restore@v6
        with:
          path: ${{ steps.args.outputs.ros2_linux_name }}.tar.bz2
          key: ${{ steps.args.outputs.ros2_linux_key }}
          fail-on-cache-miss: false

      - name: 压缩docker镜像
        if: steps.docker_cache.outputs.cache-hit == 'true'
        run: |
          tar -cavf ${{ steps.args.outputs.image_name }}.tar.bz2 ${{ steps.args.outputs.image_name }}.tar

      - name: 上传Docker镜像
        if: steps.docker_cache.outputs.cache-hit == 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.args.outputs.tag_name }}
          name: Release ${{ steps.args.outputs.tag_name }}
          prerelease: false
          draft: false
          generate_release_notes: true
          files: ${{ steps.args.outputs.image_name }}.tar.bz2

      - name: 上传Linux Ros2编译结果
        if: steps.ros2_linux_cache.outputs.cache-hit == 'true'
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.args.outputs.tag_name }}
          name: Release ${{ steps.args.outputs.tag_name }}
          prerelease: false
          draft: false
          generate_release_notes: true
          files: ${{ steps.args.outputs.ros2_linux_name }}.tar.bz2
